travis:
  secure:
    BINSTAR_TOKEN: RzXH0hLVx6tItfYgbyS4B2ByMle0S2IPX2X2plksPwByaBr1W4xNvN4+zEjjMY5y92IGdu48xhJNCBE6vMF+jUUsDFg822W6KFLvfNy4u9cl6x7FO5tpWwkPNpbHUPiomsIBnB8enmbUUPJ0e2o3CbYmRKf/JcjczwIH6hZ2Wi/cBq34hpj3F2Bb6yy6dNFsee95g1Q3OHNxTuXWkjpLr/aAC/rjPjSS3CTzFgFchxkHhnyKooFceNcyt9JjGLHUZmnzX8vpPTqDxrXwKfnXxJgX6Xork3MCFqtK4fIQ7U816j1sJtujinEAs2RNTJE1gEkZR0bgPhss6Gkzmbzmma+dXYQonlrkIC8CzpYyO0/XuvW9UD6bCs397E/vSt7ERhD88S+M7gxwGoFh6LrGoMyGNwBKLflMzibnbBnl+k3PVoHT3O6e+18P9CS7WWu1+CwAQq9lBTL5QcMoxMthmUAxvA9XzPwqOW+Wlsi/BGSVQYLp+x8kGHmrj1YwET8qm2q8Pce9r5Yw87ILjb29xMZv7/pjnA1PSFjdXBgdFeiXVUFdxF7e+c3ULGkPtZfJSeh6ayuojy5pESJSvg6Gpgdrcq4Mk1yapl55hk5VZ2RcCdP5xgub2INC1PqJEAJmtef+CFWOfDw0oMe8UjjItmU1T7XNW0OT7IdIy9BxNXg=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
